// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        kotlin_version = '2.2.0'
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://artifacts.applovin.com/android' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.3'
        classpath 'com.google.gms:google-services:4.5.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.8'


        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id "vkid.manifest.placeholders" version "1.1.0" apply true
}

String clientId = "51874098"
String clientSecret = "Z1WG3N8SpdQFHx9FE4eM"
// Добавление значений в Manifest Placeholders.
vkidManifestPlaceholders {
    // Добавьте плейсхолдеры сокращенным способом. Например, vkidRedirectHost будет "vk.ru", а vkidRedirectScheme будет "vk$clientId".
    init(clientId, clientSecret)
    // Или укажите значения явно через properties, если не хотите использовать плейсхолдеры.
    vkidRedirectHost = "vk.ru" // Обычно vk.ru.
    vkidRedirectScheme = "vk{$clientId}" // Строго в формате vk{ID приложения}.
    vkidClientId = clientId
    vkidClientSecret = clientSecret
}

allprojects {
    repositories {
        mavenCentral()
        maven { url 'https://artifactory-external.vkpartner.ru/artifactory/vkid-sdk-android/' }
        maven { url 'https://artifactory-external.vkpartner.ru/artifactory/maven/' }
        maven { url 'https://artifactory-external.vkpartner.ru/artifactory/vk-id-captcha/android/' }
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}